# Generated by Django 5.0.6 on 2024-06-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0002_alter_empresa_options_alter_mentor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'Mentor', 'verbose_name_plural': 'Mentores'},
        ),
    ]
