# Generated by Django 5.0.6 on 2024-06-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0003_alter_empresa_options_alter_mentor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'aluno'), (2, 'mentor'), (3, 'empresa')], null=True),
        ),
    ]
