# Generated by Django 5.0.6 on 2024-06-24 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0005_alter_aluno_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetovida',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_vida', to='GPC.aluno'),
            preserve_default=False,
        ),
    ]
