# Generated by Django 5.0.6 on 2024-06-24 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0006_projetovida_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='projetos_de_vida',
            field=models.ManyToManyField(blank=True, related_name='alunos', to='GPC.projetovida', verbose_name='Projetos de Vida'),
        ),
        migrations.AlterField(
            model_name='projetovida',
            name='aluno',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_vida', to='GPC.aluno'),
        ),
    ]
