# Generated by Django 5.0.6 on 2024-06-24 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0008_remove_aluno_projetos_de_vida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='disponibilidade_mentoria',
        ),
        migrations.AddField(
            model_name='mentor',
            name='area_mentoria',
            field=models.CharField(choices=[('analise_quantitativa', 'Análise Quantitativa'), ('pesquisa_operacional', 'Pesquisa Operacional'), ('ensino', 'Ensino e Educação'), ('estatistica_aplicada', 'Estatística Aplicada'), ('desenvolvimento_software', 'Desenvolvimento de Software'), ('seguranca_cibernetica', 'Segurança Cibernética'), ('gestao_de_ti', 'Gestão de TI'), ('inteligencia_artificial', 'Inteligência Artificial'), ('ciencia_dados_aplicada', 'Ciência de Dados Aplicada'), ('analise_dados', 'Análise de Dados'), ('engenharia_de_dados', 'Engenharia de Dados'), ('governanca_de_dados', 'Governança de Dados'), ('pesquisa_academica', 'Pesquisa Acadêmica da Física'), ('fisica_medica', 'Física Médica'), ('nanotecnologia', 'Nanotecnologia'), ('energia_sustentabilidade', 'Energia e Sustentabilidade'), ('biofisica', 'Biofísica'), ('astronomia', 'Astronomia'), ('climatolofia_metereologia', 'Climatologia e Metereologia')], default='biofisica', max_length=100, verbose_name='Mentoria'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Mentoriaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField(verbose_name='Área da Mentoria')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de fim')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPC.aluno', verbose_name='Aluno')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPC.mentor', verbose_name='Mentor')),
            ],
            options={
                'verbose_name': 'Mentoria',
                'verbose_name_plural': 'Mentorias',
                'ordering': ['data_inicio'],
            },
        ),
    ]
