# Generated by Django 5.0.6 on 2024-06-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0009_remove_mentor_disponibilidade_mentoria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentoriaa',
        ),
    ]
