# Generated by Django 5.0.6 on 2024-06-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0011_rename_estagio_vaga_alter_vaga_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='mentoria',
        ),
        migrations.AddField(
            model_name='aluno',
            name='mentoria_ativa',
            field=models.BooleanField(default=False, verbose_name='Mentoria Ativa'),
        ),
    ]
