# Generated by Django 5.0.6 on 2024-06-27 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0012_remove_aluno_mentoria_aluno_mentoria_ativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='mentoria_ativa',
        ),
    ]
