# Generated by Django 5.0.6 on 2024-06-27 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0013_remove_aluno_mentoria_ativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField(verbose_name='Área da Mentoria')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de início')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de fim')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPC.aluno', verbose_name='Aluno')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPC.mentor', verbose_name='Mentor')),
            ],
            options={
                'verbose_name': 'Mentoria',
                'verbose_name_plural': 'Mentorias',
                'ordering': ['data_inicio'],
            },
        ),
    ]
