# Generated by Django 5.0.6 on 2024-06-30 22:41

import GPC.models.projetovida
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0014_mentoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='slug',
            field=models.SlugField(default='titulo', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentoria',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de fim'),
        ),
        migrations.AlterField(
            model_name='projetovida',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to=GPC.models.projetovida.upload_to),
        ),
    ]
