# Generated by Django 5.0.6 on 2024-07-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0015_vaga_slug_alter_mentoria_data_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='data_encerramento',
            field=models.DateField(verbose_name='Data de Encerramento'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='data_publicacao',
            field=models.DateField(verbose_name='Data de Publicação'),
        ),
    ]
