# Generated by Django 5.0.6 on 2024-07-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0016_alter_vaga_data_encerramento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='data_publicacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Publicação'),
        ),
    ]
