# Generated by Django 5.0.6 on 2024-07-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0017_alter_vaga_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoria',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='mentoria',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de solicitação'),
        ),
    ]
