# Generated by Django 5.0.6 on 2024-07-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0018_alter_mentoria_data_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='enfase',
            field=models.CharField(choices=[('MAT', 'Matemática'), ('FIS', 'Física'), ('CS', 'Ciência da Computação'), ('DS', 'Ciência de Dados')], default='MAT', max_length=100, verbose_name='Enfase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('MTI', 'Bacharelado em Matemática da Tecnologia e Inovação')], max_length=100, verbose_name='Curso'),
        ),
    ]
