# Generated by Django 5.0.6 on 2024-07-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0019_aluno_enfase_alter_aluno_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='enfase',
            field=models.CharField(choices=[('MAT', 'Matemática'), ('FIS', 'Física'), ('CS', 'Ciência da Computação'), ('DS', 'Ciência de Dados')], default='MAT', max_length=100, verbose_name='Enfase'),
            preserve_default=False,
        ),
    ]
