# Generated by Django 5.0.6 on 2024-07-13 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0021_curriculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoconhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etica', models.TextField(blank=True, null=True)),
                ('autoeficacia', models.TextField(blank=True, null=True)),
                ('trabalho_equipe', models.TextField(blank=True, null=True)),
                ('pens_criativo', models.TextField(blank=True, null=True)),
                ('pens_analitico', models.TextField(blank=True, null=True)),
                ('res_problemas', models.TextField(blank=True, null=True)),
                ('comunicacao', models.TextField(blank=True, null=True)),
                ('adaptabilidade', models.TextField(blank=True, null=True)),
                ('persistencia', models.TextField(blank=True, null=True)),
                ('agilidade', models.TextField(blank=True, null=True)),
                ('gestao', models.TextField(blank=True, null=True)),
                ('orient_cliente', models.TextField(blank=True, null=True)),
                ('linguagens', models.TextField(blank=True, null=True)),
                ('programacao', models.TextField(blank=True, null=True)),
                ('ia', models.TextField(blank=True, null=True)),
                ('bigdata', models.TextField(blank=True, null=True)),
                ('ciberseg', models.TextField(blank=True, null=True)),
                ('redes', models.TextField(blank=True, null=True)),
                ('qualidade', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='autoconhecimento', to='GPC.aluno')),
            ],
        ),
    ]
