# Generated by Django 5.0.6 on 2024-07-15 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0023_alter_autoconhecimento_adaptabilidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanejamentoCarreira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matematica', models.BooleanField(default=False)),
                ('fisica', models.BooleanField(default=False)),
                ('ciencia_informacao', models.BooleanField(default=False)),
                ('ciencia_dados', models.BooleanField(default=False)),
                ('empresas_cargos', models.CharField(max_length=255)),
                ('objetivos_carreira', models.TextField()),
                ('motivacoes_profissionais', models.TextField()),
                ('desafios', models.TextField()),
                ('machine_learning', models.BooleanField(default=False)),
                ('nlp', models.BooleanField(default=False)),
                ('computer_vision', models.BooleanField(default=False)),
                ('big_data', models.BooleanField(default=False)),
                ('cloud_computing', models.BooleanField(default=False)),
                ('communication', models.BooleanField(default=False)),
                ('teamwork', models.BooleanField(default=False)),
                ('problem_solving', models.BooleanField(default=False)),
                ('critical_thinking', models.BooleanField(default=False)),
                ('continuous_learning', models.BooleanField(default=False)),
                ('project_development', models.BooleanField(default=False)),
                ('internships', models.BooleanField(default=False)),
                ('open_source', models.BooleanField(default=False)),
                ('competitions', models.BooleanField(default=False)),
                ('networking', models.BooleanField(default=False)),
                ('events', models.BooleanField(default=False)),
                ('online_communities', models.BooleanField(default=False)),
                ('scientific_publications', models.BooleanField(default=False)),
                ('conferences', models.BooleanField(default=False)),
                ('online_courses', models.BooleanField(default=False)),
                ('online_communities_update', models.BooleanField(default=False)),
                ('events_connection', models.BooleanField(default=False)),
                ('online_communities_connection', models.BooleanField(default=False)),
                ('open_source_connection', models.BooleanField(default=False)),
                ('mentor', models.BooleanField(default=False)),
                ('competitions_connection', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('present_work', models.BooleanField(default=False)),
                ('volunteer', models.BooleanField(default=False)),
                ('goal_setting', models.BooleanField(default=False)),
                ('regular_monitoring', models.BooleanField(default=False)),
                ('self_assessment', models.BooleanField(default=False)),
                ('external_feedback', models.BooleanField(default=False)),
                ('portfolio', models.BooleanField(default=False)),
                ('kpi', models.BooleanField(default=False)),
                ('reflection', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='planejamento_carreira', to='GPC.aluno')),
            ],
        ),
    ]
