# Generated by Django 5.0.6 on 2024-07-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0023_alter_autoconhecimento_adaptabilidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetovida',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
