# Generated by Django 5.0.6 on 2024-07-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0024_planejamentocarreira'),
        ('GPC', '0024_projetovida_linkedin'),
    ]

    operations = [
    ]
