# Generated by Django 5.0.6 on 2024-07-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0025_merge_20240715_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='adaptabilidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='agilidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='autoeficacia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='bigdata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='ciberseg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='comunicacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='etica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='gestao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='ia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='linguagens',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='orient_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='pens_analitico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='pens_criativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='persistencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='programacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='qualidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='redes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='res_problemas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaga',
            name='trabalho_equipe',
            field=models.BooleanField(default=False),
        ),
    ]
