# Generated by Django 5.0.6 on 2024-07-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0026_vaga_adaptabilidade_vaga_agilidade_vaga_autoeficacia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='etica',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
