# Generated by Django 5.0.6 on 2024-07-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0027_alter_vaga_etica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='etica',
            field=models.BooleanField(default=False),
        ),
    ]
