# Generated by Django 5.0.6 on 2024-07-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0028_alter_vaga_etica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='enfase',
            field=models.CharField(choices=[('MAT', 'Matemática'), ('FIS', 'Física'), ('CS', 'Ciência da Computação'), ('DS', 'Ciência de Dados')], max_length=100, verbose_name='Enfase da Vaga'),
        ),
    ]
