# Generated by Django 5.0.6 on 2024-08-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0031_gestor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255, unique=True)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
            ],
        ),
    ]
