# Generated by Django 5.0.6 on 2024-08-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0032_pageconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='enfase',
        ),
        migrations.AddField(
            model_name='vaga',
            name='tipo_vaga',
            field=models.CharField(choices=[('TRA', 'Trainee'), ('EST', 'Estágio'), ('JVM', 'Jovem Aprendiz'), ('IC', 'Iniciação Científica'), ('EXT', 'Bolsa de Extensão')], default='EST', max_length=100, verbose_name='Tipo da Vaga'),
            preserve_default=False,
        ),
    ]
