# Generated by Django 5.0.6 on 2024-08-06 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0033_remove_vaga_enfase_vaga_tipo_vaga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='enfase',
        ),
    ]
