# Generated by Django 5.0.7 on 2024-08-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0036_customuser_planejamento_preenchido'),
    ]

    operations = [
        migrations.AddField(
            model_name='planejamentocarreira',
            name='GTD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planejamentocarreira',
            name='Ivy_Lee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planejamentocarreira',
            name='Kanban',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planejamentocarreira',
            name='Pomodoro',
            field=models.IntegerField(default=0),
        ),
    ]
