# Generated by Django 5.0.7 on 2024-08-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0037_planejamentocarreira_gtd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planejamentocarreira',
            old_name='GTD',
            new_name='gtd_score',
        ),
        migrations.RenameField(
            model_name='planejamentocarreira',
            old_name='Ivy_Lee',
            new_name='ivy_lee_score',
        ),
        migrations.RenameField(
            model_name='planejamentocarreira',
            old_name='Kanban',
            new_name='kanban_score',
        ),
        migrations.RenameField(
            model_name='planejamentocarreira',
            old_name='Pomodoro',
            new_name='pomodoro_score',
        ),
        migrations.AddField(
            model_name='planejamentocarreira',
            name='melhor_metodologia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
