# Generated by Django 5.0.6 on 2024-08-11 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0039_remove_estudo_recomendacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aceito', 'Aceito'), ('Recusado', 'Recusado')], default='Pendente', max_length=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Solicitação')),
                ('data_decisao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Decisão')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='GPC.aluno')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='GPC.vaga')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'unique_together': {('aluno', 'vaga')},
            },
        ),
    ]
