# Generated by Django 5.0.7 on 2024-08-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0040_alunovaga'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanejamentoParametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GTD', models.IntegerField(default=0)),
                ('Kanban', models.IntegerField(default=0)),
                ('Pomodoro', models.IntegerField(default=0)),
                ('Ivy_Lee', models.IntegerField(default=0)),
            ],
        ),
    ]
