# Generated by Django 5.0.6 on 2024-08-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0040_alunovaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='area_mentoria',
            field=models.CharField(choices=[('analise_quantitativa', 'Análise Quantitativa'), ('pesquisa_operacional', 'Pesquisa Operacional'), ('ensino', 'Ensino e Educação'), ('estatistica_aplicada', 'Estatística Aplicada'), ('desenvolvimento_software', 'Desenvolvimento de Software'), ('seguranca_cibernetica', 'Segurança Cibernética'), ('gestao_de_ti', 'Gestão de TI'), ('inteligencia_artificial', 'Inteligência Artificial'), ('ciencia_dados_aplicada', 'Ciência de Dados Aplicada'), ('analise_dados', 'Análise de Dados'), ('engenharia_de_dados', 'Engenharia de Dados'), ('governanca_de_dados', 'Governança de Dados'), ('pesquisa_academica', 'Pesquisa Acadêmica da Física'), ('fisica_medica', 'Física Médica'), ('nanotecnologia', 'Nanotecnologia'), ('energia_sustentabilidade', 'Energia e Sustentabilidade'), ('biofisica', 'Biofísica'), ('astronomia', 'Astronomia'), ('climatolofia_metereologia', 'Climatologia e Metereologia'), ('analise_numerica', 'Análise Numérica'), ('estatistica', 'Estatística'), ('big_data', 'Big Data'), ('machine_learning', 'Machine Learning'), ('visualizacao_dados', 'Visualização de Dados'), ('algoritmos', 'Algoritmos e Estruturas de Dados'), ('seguranca_informacao', 'Segurança da Informação'), ('fisica_computacional', 'Física Computacional'), ('modelagem_simulacao', 'Modelagem e Simulação'), ('inteligencia_artificial_aplicada', 'Inteligência Artificial Aplicada')], max_length=100, verbose_name='Mentoria'),
        ),
        migrations.AlterField(
            model_name='projetovida',
            name='area_interesse',
            field=models.CharField(choices=[('analise_quantitativa', 'Análise Quantitativa'), ('pesquisa_operacional', 'Pesquisa Operacional'), ('ensino', 'Ensino e Educação'), ('estatistica_aplicada', 'Estatística Aplicada'), ('desenvolvimento_software', 'Desenvolvimento de Software'), ('seguranca_cibernetica', 'Segurança Cibernética'), ('gestao_de_ti', 'Gestão de TI'), ('inteligencia_artificial', 'Inteligência Artificial'), ('ciencia_dados_aplicada', 'Ciência de Dados Aplicada'), ('analise_dados', 'Análise de Dados'), ('engenharia_de_dados', 'Engenharia de Dados'), ('governanca_de_dados', 'Governança de Dados'), ('pesquisa_academica', 'Pesquisa Acadêmica da Física'), ('fisica_medica', 'Física Médica'), ('nanotecnologia', 'Nanotecnologia'), ('energia_sustentabilidade', 'Energia e Sustentabilidade'), ('biofisica', 'Biofísica'), ('astronomia', 'Astronomia'), ('climatolofia_metereologia', 'Climatologia e Metereologia'), ('analise_numerica', 'Análise Numérica'), ('estatistica', 'Estatística'), ('big_data', 'Big Data'), ('machine_learning', 'Machine Learning'), ('visualizacao_dados', 'Visualização de Dados'), ('algoritmos', 'Algoritmos e Estruturas de Dados'), ('seguranca_informacao', 'Segurança da Informação'), ('fisica_computacional', 'Física Computacional'), ('modelagem_simulacao', 'Modelagem e Simulação'), ('inteligencia_artificial_aplicada', 'Inteligência Artificial Aplicada')], max_length=50),
        ),
    ]
