# Generated by Django 5.0.6 on 2024-08-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0041_remove_pageconfiguration_element_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementconfiguration',
            name='background_color',
            field=models.CharField(blank=True, max_length=15, verbose_name='Cor de Fundo'),
        ),
        migrations.AlterField(
            model_name='elementconfiguration',
            name='element_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Elemento'),
        ),
        migrations.AlterField(
            model_name='elementconfiguration',
            name='text_color',
            field=models.CharField(blank=True, max_length=15, verbose_name='Cor do Texto'),
        ),
    ]
