# Generated by Django 5.0.6 on 2024-08-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0042_alter_elementconfiguration_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementconfiguration',
            name='background_color',
            field=models.CharField(max_length=15, null=True, verbose_name='Cor de Fundo'),
        ),
        migrations.AlterField(
            model_name='elementconfiguration',
            name='element_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome do Elemento'),
        ),
        migrations.AlterField(
            model_name='elementconfiguration',
            name='text_color',
            field=models.CharField(max_length=15, null=True, verbose_name='Cor do Texto'),
        ),
        migrations.AlterField(
            model_name='pageconfiguration',
            name='elements',
            field=models.ManyToManyField(null=True, to='GPC.elementconfiguration', verbose_name='Elementos'),
        ),
        migrations.AlterField(
            model_name='pageconfiguration',
            name='icon',
            field=models.ImageField(null=True, upload_to='icons/'),
        ),
    ]
