# Generated by Django 5.0.6 on 2024-08-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0041_alter_mentor_area_mentoria_and_more'),
        ('GPC', '0044_alter_pageconfiguration_elements'),
    ]

    operations = [
    ]
