# Generated by Django 5.0.7 on 2024-08-21 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPC', '0041_planejamentoparametros'),
        ('GPC', '0045_merge_20240816_1621'),
    ]

    operations = [
    ]
